name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build package
      run: |
        echo "Building package..."
        zip -r calculator.zip calculator.py

    - name: Deploy
      run: |
        echo "Deploying to mock environment..."
        mkdir -p deploy
        mv calculator.zip deploy/
        echo "Deployment completed at $(date)" > deploy/deployment.log
